require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BroadcastMediaController do

  # This should return the minimal set of attributes required to create a valid
  # BroadcastMedium. As you add validations to BroadcastMedium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BroadcastMediaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all broadcast_media as @broadcast_media" do
      broadcast_medium = BroadcastMedium.create! valid_attributes
      get :index, {}, valid_session
      assigns(:broadcast_media).should eq([broadcast_medium])
    end
  end

  describe "GET show" do
    it "assigns the requested broadcast_medium as @broadcast_medium" do
      broadcast_medium = BroadcastMedium.create! valid_attributes
      get :show, {:id => broadcast_medium.to_param}, valid_session
      assigns(:broadcast_medium).should eq(broadcast_medium)
    end
  end

  describe "GET new" do
    it "assigns a new broadcast_medium as @broadcast_medium" do
      get :new, {}, valid_session
      assigns(:broadcast_medium).should be_a_new(BroadcastMedium)
    end
  end

  describe "GET edit" do
    it "assigns the requested broadcast_medium as @broadcast_medium" do
      broadcast_medium = BroadcastMedium.create! valid_attributes
      get :edit, {:id => broadcast_medium.to_param}, valid_session
      assigns(:broadcast_medium).should eq(broadcast_medium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BroadcastMedium" do
        expect {
          post :create, {:broadcast_medium => valid_attributes}, valid_session
        }.to change(BroadcastMedium, :count).by(1)
      end

      it "assigns a newly created broadcast_medium as @broadcast_medium" do
        post :create, {:broadcast_medium => valid_attributes}, valid_session
        assigns(:broadcast_medium).should be_a(BroadcastMedium)
        assigns(:broadcast_medium).should be_persisted
      end

      it "redirects to the created broadcast_medium" do
        post :create, {:broadcast_medium => valid_attributes}, valid_session
        response.should redirect_to(BroadcastMedium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved broadcast_medium as @broadcast_medium" do
        # Trigger the behavior that occurs when invalid params are submitted
        BroadcastMedium.any_instance.stub(:save).and_return(false)
        post :create, {:broadcast_medium => { "name" => "invalid value" }}, valid_session
        assigns(:broadcast_medium).should be_a_new(BroadcastMedium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BroadcastMedium.any_instance.stub(:save).and_return(false)
        post :create, {:broadcast_medium => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested broadcast_medium" do
        broadcast_medium = BroadcastMedium.create! valid_attributes
        # Assuming there are no other broadcast_media in the database, this
        # specifies that the BroadcastMedium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BroadcastMedium.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => broadcast_medium.to_param, :broadcast_medium => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested broadcast_medium as @broadcast_medium" do
        broadcast_medium = BroadcastMedium.create! valid_attributes
        put :update, {:id => broadcast_medium.to_param, :broadcast_medium => valid_attributes}, valid_session
        assigns(:broadcast_medium).should eq(broadcast_medium)
      end

      it "redirects to the broadcast_medium" do
        broadcast_medium = BroadcastMedium.create! valid_attributes
        put :update, {:id => broadcast_medium.to_param, :broadcast_medium => valid_attributes}, valid_session
        response.should redirect_to(broadcast_medium)
      end
    end

    describe "with invalid params" do
      it "assigns the broadcast_medium as @broadcast_medium" do
        broadcast_medium = BroadcastMedium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BroadcastMedium.any_instance.stub(:save).and_return(false)
        put :update, {:id => broadcast_medium.to_param, :broadcast_medium => { "name" => "invalid value" }}, valid_session
        assigns(:broadcast_medium).should eq(broadcast_medium)
      end

      it "re-renders the 'edit' template" do
        broadcast_medium = BroadcastMedium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BroadcastMedium.any_instance.stub(:save).and_return(false)
        put :update, {:id => broadcast_medium.to_param, :broadcast_medium => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested broadcast_medium" do
      broadcast_medium = BroadcastMedium.create! valid_attributes
      expect {
        delete :destroy, {:id => broadcast_medium.to_param}, valid_session
      }.to change(BroadcastMedium, :count).by(-1)
    end

    it "redirects to the broadcast_media list" do
      broadcast_medium = BroadcastMedium.create! valid_attributes
      delete :destroy, {:id => broadcast_medium.to_param}, valid_session
      response.should redirect_to(broadcast_media_url)
    end
  end

end
