require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BroadcastMessagesController do

  # This should return the minimal set of attributes required to create a valid
  # BroadcastMessage. As you add validations to BroadcastMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "broadcast" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BroadcastMessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all broadcast_messages as @broadcast_messages" do
      broadcast_message = BroadcastMessage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:broadcast_messages).should eq([broadcast_message])
    end
  end

  describe "GET show" do
    it "assigns the requested broadcast_message as @broadcast_message" do
      broadcast_message = BroadcastMessage.create! valid_attributes
      get :show, {:id => broadcast_message.to_param}, valid_session
      assigns(:broadcast_message).should eq(broadcast_message)
    end
  end

  describe "GET new" do
    it "assigns a new broadcast_message as @broadcast_message" do
      get :new, {}, valid_session
      assigns(:broadcast_message).should be_a_new(BroadcastMessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested broadcast_message as @broadcast_message" do
      broadcast_message = BroadcastMessage.create! valid_attributes
      get :edit, {:id => broadcast_message.to_param}, valid_session
      assigns(:broadcast_message).should eq(broadcast_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BroadcastMessage" do
        expect {
          post :create, {:broadcast_message => valid_attributes}, valid_session
        }.to change(BroadcastMessage, :count).by(1)
      end

      it "assigns a newly created broadcast_message as @broadcast_message" do
        post :create, {:broadcast_message => valid_attributes}, valid_session
        assigns(:broadcast_message).should be_a(BroadcastMessage)
        assigns(:broadcast_message).should be_persisted
      end

      it "redirects to the created broadcast_message" do
        post :create, {:broadcast_message => valid_attributes}, valid_session
        response.should redirect_to(BroadcastMessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved broadcast_message as @broadcast_message" do
        # Trigger the behavior that occurs when invalid params are submitted
        BroadcastMessage.any_instance.stub(:save).and_return(false)
        post :create, {:broadcast_message => { "broadcast" => "invalid value" }}, valid_session
        assigns(:broadcast_message).should be_a_new(BroadcastMessage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BroadcastMessage.any_instance.stub(:save).and_return(false)
        post :create, {:broadcast_message => { "broadcast" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested broadcast_message" do
        broadcast_message = BroadcastMessage.create! valid_attributes
        # Assuming there are no other broadcast_messages in the database, this
        # specifies that the BroadcastMessage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BroadcastMessage.any_instance.should_receive(:update).with({ "broadcast" => "" })
        put :update, {:id => broadcast_message.to_param, :broadcast_message => { "broadcast" => "" }}, valid_session
      end

      it "assigns the requested broadcast_message as @broadcast_message" do
        broadcast_message = BroadcastMessage.create! valid_attributes
        put :update, {:id => broadcast_message.to_param, :broadcast_message => valid_attributes}, valid_session
        assigns(:broadcast_message).should eq(broadcast_message)
      end

      it "redirects to the broadcast_message" do
        broadcast_message = BroadcastMessage.create! valid_attributes
        put :update, {:id => broadcast_message.to_param, :broadcast_message => valid_attributes}, valid_session
        response.should redirect_to(broadcast_message)
      end
    end

    describe "with invalid params" do
      it "assigns the broadcast_message as @broadcast_message" do
        broadcast_message = BroadcastMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BroadcastMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => broadcast_message.to_param, :broadcast_message => { "broadcast" => "invalid value" }}, valid_session
        assigns(:broadcast_message).should eq(broadcast_message)
      end

      it "re-renders the 'edit' template" do
        broadcast_message = BroadcastMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BroadcastMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => broadcast_message.to_param, :broadcast_message => { "broadcast" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested broadcast_message" do
      broadcast_message = BroadcastMessage.create! valid_attributes
      expect {
        delete :destroy, {:id => broadcast_message.to_param}, valid_session
      }.to change(BroadcastMessage, :count).by(-1)
    end

    it "redirects to the broadcast_messages list" do
      broadcast_message = BroadcastMessage.create! valid_attributes
      delete :destroy, {:id => broadcast_message.to_param}, valid_session
      response.should redirect_to(broadcast_messages_url)
    end
  end

end
